### ISSUE TITLE
Output all results

### ISSUE THREAD

**Issue by ziejan** [MDU-PHL/sixess#8]
Hi,
this is not really an issue and I haven't testet the software yet but I'm interested in the output. Is it possible to output all results instead of just the top hit?
We want to get the diversity out of many reads in one fastq file after we Nanopore sequenced a microbiome.
As far as I understand your Software it does everything we want like mapping the 16s reads against ncbi, silva and rdp database (without 16s amplification?) and then outputting the hits. So maybe there is an option to output all results or a simple addition in the source code we can write?

Thank you in advance.
Jan

**Comment by tseemann** [comment]
This software was designed with illumina reads in mind, and even then doesn't work that well.

Maybe try Kraken 2 with the RDP database option?

The command here would need to be changed
eg. change `head -n 1` to `head -n 100` on this line to get 100 top results instead:
https://github.com/tseemann/sixess/blob/master/bin/sixess#L157
But then it would need to print them all out etc

**Comment by ziejan** [comment]
OK. Thank you! 
So you wouldn't recommend using sixess with Nanopore Reads? Is there any reason it shouldn't work with longer error prone reads?

I will try Kraken aswell.

**Comment by tseemann** [comment]
It doesn't even work with Illumina reads.
The mapping isn't the problem.
It's the scoring function.
RDP uses a wierd system but it clearly because it works.
The README of this repo clearly says "BETA :warning: " on it.
Please don't do any science using this!
